name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.AWS_LIGHTSAIL }}" > ~/.ssh/id_rsa
          ssh-keyscan -H "${{ vars.IP }}" > ~/.ssh/known_hosts
      - name: Deploy with git pull and running update.sh on the instance
        run: |
          echo "Deploying to ${{ vars.IP }} ..."
          ssh -i ~/.ssh/id_rsa ubuntu@"${{ vars.IP }}" "cd ITP_3-Python_Final_Bot && git checkout -- . && git pull && chmod u+x update.sh && ./update.sh"